version: "3.9"

services:
  delivery.api:
    ports:
      - "443:443"
  
  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
  
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_password
      MYSQL_DATABASE: delivery_db
      MYSQL_USER: delivery_db_user
      MYSQL_PASSWORD: delivery_db_password
    ports:
      - "3306:3306"
        
  elasticsearch:
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"