version: "3.9"

services:
  delivery.api:
    image: ${DOCKER_REGISTRY-}delivery.api
    build:
      context: .
      dockerfile: DeliveryApi/Dockerfile
    restart: always
    
  delivery.background:
    image: ${DOCKER_REGISTRY-}delivery.background
    build:
      context: .
      dockerfile: DeliveryBackground/Dockerfile
    restart: always
        
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    
  mysql:
    image: mysql:8.0.33
    restart: always
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    restart: always
    
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    restart: always
    
  mongodb:
    image: mongo
    restart: always
    
  mongo-express:
    image: mongo-express
    restart: always