version: "3.9"

services:
  delivery.api:
    environment:
      - AppSettings__Secret=03609307-0bb7-40cf-83c2-9998a50d0aff
        
      - ElasticSearchConfiguration__ConnectionString=http://elasticsearch:9200
      
      - MongoDbConfiguration__ConnectionString=mongodb://root:example@localhost:27017
      - MongoDbConfiguration__Database=DeliveryApi
        
      - RabbitMqConfiguration__HostName=rabbitmq
      - RabbitMqConfiguration__UserName=guest
      - RabbitMqConfiguration__Password=guest
      - RabbitMqConfiguration__ExchangeName=delivery-exchange
        
      - Serilog__MinimumLevel__Default=Information
      - Serilog__MinimumLevel__Override__Microsoft=Information
      - Serilog__MinimumLevel__Override__System=Warning
      - Serilog__Properties__Application=delivery-api
      - AllowedHosts=*
    ports:
      - "80:80"
      - "443:443"
    
  delivery.background:
    environment:
      - ElasticSearchConfiguration__ConnectionString=http://elasticsearch:9200

      - MongoDbConfiguration__ConnectionString=mongodb://root:example@localhost:27017
      - MongoDbConfiguration__Database=DeliveryApi

      - RabbitMqConfiguration__HostName=rabbitmq
      - RabbitMqConfiguration__UserName=guest
      - RabbitMqConfiguration__Password=guest
      - RabbitMqConfiguration__ExchangeName=delivery-exchange-expiry

      - Serilog__MinimumLevel__Default=Information
      - Serilog__MinimumLevel__Override__Microsoft=Information
      - Serilog__MinimumLevel__Override__System=Warning
      - Serilog__Properties__Application=delivery-background
  
  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
        
  elasticsearch:
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
    
  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  
  mongo-express:
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: basic-user
      ME_CONFIG_BASICAUTH_PASSWORD: basic-user-password
    ports:
      - "8081:8081"